### PR TITLE
making compatible with python3, keeping backward compat to 2.7+

### PR DESCRIPTION
**Pull request by theodoregoetz**
also added a .gitignore file with common patterns for python, C++ and Java

### CODE REVIEW

**Comment by theodoregoetz** [comment]
This pull request has now been tested and is being used in production for CLAS12 with both python 3.4.1 and 2.7.8

There are [well known issues](https://docs.python.org/3/howto/pyporting.html) about Exception handling (among others) that makes supporting 2.6 and 3.x at the same time untenable.

**Comment by DraTeots** [comment]
Hi! Thank you for the pull request. I'll merge in on the next tag (actually have some changes that require testing).

Just letting you know, that I'm aware of the pull request and deeply appreciate the work.

**Comment by theodoregoetz** [comment]
Hey great! Thanks for letting me know you saw it. I figured it was just a
matter of time.

**Comment by theodoregoetz** [comment]
ping on this pull request. Any news?

**Pull request merged**
